### ISSUE TITLE
Separar Jekyll del sitio

### ISSUE THREAD

**Issue by iblancasa** [libreim/blog#109]
Me explico:
para facilitar el despliegue, modificación de ficheros y mil cosas más, deberíais separar los ficheros de Jekyll de los generados.
Por ejemplo (creo que la mejor opción), dejando los ficheros de Jekyll en la rama master y los generados a la rama gh-pages.

**Comment by fdavidcl** [comment]
Hecho: los cambios que se hagan en la rama `sites` se compilan desde Travis y se envían al repo [libreim.github.io](https://github.com/libreim/libreim.github.io).
