### ISSUE TITLE
Creación de posts

### ISSUE THREAD

**Issue by robertohueso** [libreim/blog#110]
Para facilitar la colaboración al blog ahora que disponemos de servidor ¿Deberíamos montar un editor de Markdown online? ¿Identificar al editor con su cuenta de Github?

**Comment by fdavidcl** [comment]
Podríamos montar una paginilla que haga pull requests a través de @dgiimbot. Estoy buscando scriptsdebash o gemas de Ruby que hagan pull requests. Parece que [tonchis/git-pull-request](https://github.com/tonchis/git-pull-request) puede ser una buena opción.

**Comment by M42** [comment]
Entiendo que todo esto lo solucionó ya @fdavidcl con el sistema para añadir recursos nuevos (en https://libreim.github.io/recursos/new/). Cierro la issue, si veis que falta algo se puede reabrir.
