### ISSUE TITLE
Plugins para Jekyll

### ISSUE THREAD

**Issue by M42** [libreim/blog#126]
Ahora que no dependemos de los servidores de github, podemos ejecutar código de los plugins de Jekyll. Podemos añadir:
- [ ] [Generador de archivos](https://gist.github.com/ilkka/707909)
- [ ] [Coloreado de sintaxis en línea](https://github.com/bdesham/inline_highlight)
- [ ] Minimizador de CSS y Javascript

**Comment by M42** [comment]
Como ahora dependemos de los servidores de GitHub y esto no parece totalmente necesario; podemos ahorrárnoslo. Si es necesario puede reabrirse en un futuro.

**Comment by M42** [comment]
Las tres issues que dependían de esta quizá deberían cerrarse también. No sé si se pueden resolver si queremos depender sólo de los servers de github.

**Comment by fdavidcl** [comment]
No es que no podamos (e.g. estamos usando [este plugin](https://github.com/libreim/blog/blob/sites/_plugins/_tag_index.rb)), pero habría que ver si siguen haciendo falta/siendo útiles.
