### ISSUE TITLE
Post sobre inducción estructural

### ISSUE THREAD

**Issue by gDanix** [libreim/blog#151]
Entre unas cosas y otras, nunca he podido aportar nada al blog, pero creo que tengo algo que os puede interesar: [Inducción estructural](https://es.wikipedia.org/wiki/Inducci%C3%B3n_estructural).

Aprendí sobre ella en un curso de Scala y creo que puedo escribir un post interesante. Me parece una forma muy chula de aplicar matemáticas para demostrar la correctitud de un programa.

¿Qué os parece?

**Comment by fdavidcl** [comment]
Hola Dani!

Gracias por la sugerencia, pero creo que @M42 [se te adelantó](https://libreim.github.io/blog/2015/03/14/induccion-estructural/) 😅

**Comment by gDanix** [comment]
Jo, es verdad.

Pues nada, a seguir investigando xD
