### ISSUE TITLE
Llevar los posts a otro repositorio

### ISSUE THREAD

**Issue by M42** [libreim/blog#52]
Para separar por lado posts, y por otro, código del blog. Así nos evitaríamos mezclar commits y nos ahorraríamos que los líos y los fallos de una no afectaran a otra.

Propongo dejarlo para _después_ del hackathon.

**Comment by JJ** [comment]
Podéis usar submódulos de git:
http://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by M42** [comment]
Opciones:
* **Usar submódulos de git.** Tenemos que comprobar que se integren bien en GitHub y que separen realmente las dos partes del proyecto (blog y posts).
* **Separar en dos repositorios, de forma que los administradores puedan copiar los posts al primero.** Que es una chapuza, porque al final los posts vuelven a estar en el repositorio inicial y el código no es independiente.

La idea es que queremos que el blog en sí sea una plantilla para blogs colaborativos, y por eso el contenido debería estar lo más separado posible del blog en sí.

**Comment by JJ** [comment]
También podéis usar git hooks, de forma que tengáis el código en una rama y el resultado en otra rama diferente.

**Comment by M42** [comment]
Hemos empezado a usar un sólo repositorio para todos los sitios de LibreIM, entiendo que esta issue se puede cerrar.
