### ISSUE TITLE
Reescribir el readme.md

### ISSUE THREAD

**Issue by M42** [libreim/blog#7]
Explicando la motivación y objetivo del blog y añadiendo un pequeño "Quiénes somos".

**Comment by M42** [comment]
Y podríamos pasar la explicación del blog al post sobre eso. #97

**Comment by andreshp** [comment]
Un caso particular es la issue #66: añadir las funcionalidades de rake post al README.md

**Comment by M42** [comment]
Queda cerrada con #118.
