### ISSUE TITLE
¿Cómo añadir problemas al blog?

### ISSUE THREAD

**Issue by andreshp** [libreim/blog#79]
Estaría genial proponer problemas cada cierto periodo de tiempo (mantiene el blog más activo, requiere menos trabajo que un artículo entero, etc). ¿Cómo debería llevarse a cabo?

- En Gaussianos los proponen como un post normal (sin la solución).
- Otra opción sería tener una zona del blog explícita para ello.

¿Alguna propuesta?

**Comment by fdavidcl** [comment]
Lo más directo es hacer posts normales, asignarles la categoría `problema` (o similar) y crear una página `problemas.html` (con url `/blog/problemas` o algo así) que liste sólo los posts de esa categoría.

Si se os ocurren otras ideas comentadlas aquí, y vemos cómo se pueden llevar a cabo.

**Comment by M42** [comment]
En las reuniones de Python Granada se ha comentado la posibilidad de hacer concursos (desafíos). No sé cómo se pretendía llevar a cabo, pero quizá un formato similar podría servir tanto para problemas de informática como de matemáticas.

**Comment by JJ** [comment]
Estaría guay.

**Comment by andreshp** [comment]
Hemos pensado publicar pequeños post con los enunciados y hacer que la gente envíe las soluciones a dgiim.blog+problema1@gmail.com. Cada cierto periodo de tiempo realizaríamos un seminario en el que se discutan las soluciones.

**Comment by M42** [comment]
Hay que tener en cuenta que por otro lado tenemos overflow para plantear problemas.

**Comment by M42** [comment]
Creo que entre la solución de overflow y la idea de los post con enunciados, esta issue estaría resuelta. Cierro.
